// Extracts class portraits from game-icons.net (CC BY 3.0) into a small
// generated module, so the web app doesn't bundle the whole icon set.
// Run: node tools/portraits.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';

const require = createRequire(
  new URL('../apps/web/package.json', import.meta.url),
);
const set = JSON.parse(
  readFileSync(require.resolve('@iconify-json/game-icons/icons.json'), 'utf8'),
);

const portraits = {
  knight: { icon: 'visored-helm' },
  crossbowman: { icon: 'barbute' },
  stormcaller: { icon: 'wizard-face' },
  deathKnight: { icon: 'black-knight-helm' },
  assassin: { icon: 'hooded-assassin' },
  warlock: { icon: 'warlock-hood' },
  warden: { icon: 'tree-face' },
  ranger: { icon: 'elf-helmet' },
  druid: { icon: 'woman-elf-face' },
};

const out = Object.fromEntries(
  Object.entries(portraits).map(([id, p]) => {
    const icon = set.icons[p.icon];
    if (!icon) throw new Error(`Missing icon ${p.icon}`);
    return [id, { body: icon.body, size: set.width ?? 512, source: p.icon }];
  }),
);

writeFileSync(
  new URL('../apps/web/src/portraits.generated.ts', import.meta.url),
  `// Generated by tools/portraits.mjs. Do not edit.
// Icons by the game-icons.net contributors (Lorc, Delapouite and others),
// licensed CC BY 3.0 (https://creativecommons.org/licenses/by/3.0/).
export const portraits: Record<string, { body: string; size: number; source: string }> = ${JSON.stringify(out, null, 2)};
`,
);
console.log('wrote', Object.keys(out).length, 'portraits');
